---
title: "Auditory_FB_analyses"
author: "Lucrezia Lonardo"
date: "2024-10-22"
output: html_document
---
### Load libraries
```{r}
library(tidyverse)
library(ggplot2)
```

### Import data

```{r}
xdata <- read.csv("data/tested_dogs.csv", header = TRUE) %>% 
   mutate(choice_letter = as.factor(choice_letter),
         condition = as.factor(condition),
         age_months = as.numeric(age_months)) %>% 
  filter(choice_letter %in% c("A", "B")) %>%   # Keep rows where choice_letter is "A" or "B"
  droplevels()
```

###Descriptive statistics
```{r}
##nr. dogs choosing bucket A and B overall
table(xdata$choice_letter)

##proportions relative to the whole sample
mean(xdata$choice_letter=="A")
mean(xdata$choice_letter=="B")

##nr. dogs choosing bucket A and B in each condition
table(xdata$condition, xdata$choice_letter)

##proportions relative to the different conditions
fb_subset <- xdata[xdata$condition == "false_belief", ]
know_subset <- xdata[xdata$condition == "knowledge", ]
ctr_subset <- xdata[xdata$condition == "control", ]
mean(fb_subset$choice_letter=="A")
mean(know_subset$choice_letter=="A")
mean(ctr_subset$choice_letter=="A")

#experimenters (communicator and hider)
table(xdata$condition, xdata$communicator)
table(xdata$condition, xdata$hider)
xdata$experimenter_dyad<-paste(xdata$communicator, xdata$hider, sep="_")
table(xdata$condition, xdata$experimenter_dyad)

#age
mean(fb_subset$age_months)
mean(know_subset$age_months) #check Dali, Bo and Kunibert
mean(ctr_subset$age_months)

#sex
table(xdata$sex, xdata$condition)
```


### Plots


```{r pressure, echo=FALSE}
#table with descriptive stats for plotting
plot.data <- xdata %>%
  mutate(choice = ifelse(choice_letter == "A", 1, 0)) %>%
  mutate(condition = fct_relevel(
    fct_recode(
      condition,
      "false belief" = "false_belief",
      "knowledge" = "knowledge",
      "control" = "control"
    ),
    "false belief",
    "knowledge",
    "control"
  )) %>% #specify order of factor levels for factor_relevel
  group_by(condition) %>%
  summarise(
    mean.choiceA = mean(choice),
    sd.choiceA = sd(choice),
    n.choseA = sum(choice),
    median.choiceA = median(choice),
    n.tested.per.cond = length(choice),
    se.choiceA = sd(choice) / sqrt(length(choice))
  )

plot.data

##barplot of choices by experimental group

p.choice <- ggplot(data = plot.data, aes(x = condition, y = mean.choiceA)) +
  geom_bar(stat = "identity", alpha = 0.5) +
  geom_errorbar(aes(ymin = mean.choiceA - se.choiceA, ymax = mean.choiceA + #error bars represent standard error
                      se.choiceA),
                width = .2) +
  #geom_signif(comparisons=list(c("False Belief", #"Knowledge")), annotations="*",
  #             y_position = 0.75, tip_length = 0.04, #vjust=0.4) +
  #ylim(0.2,0.6)+
  theme_classic() +
  labs(x = "Experimental group", y = "Proportion of bucket A choices")+
  ggtitle("All breeds (N=91)")

p.choice
 
#saving the plot with ggsave
# ggsave(
#   "./graphs/bucket_A_choices_BC.png",
#   plot = last_plot(),
#   device = NULL,
#  # path = "C:/Users/lonardol/Desktop/False Belief experiment/FB_2_follow_up/Graphs/Border Collies",
#   scale = 0.8,
#   width = 7,
#   height = 6,
#   #units = c("in", "cm", "mm"),
#   dpi = 320,
#   limitsize = TRUE
# )
```

```{r}
#mosaic plot to visualize also bucket B choices
mosaic.plot.data  <- xdata %>%
  mutate(choice_letter = fct_relevel(choice_letter, "B", "A")) %>%
  mutate(condition = fct_relevel(
    fct_recode(
      condition,
      "False belief" = "false_belief",
      "True Belief" = "knowledge",
      "Sound Control" = "control"
    ),
    "False belief",
    "True Belief",
    "Sound Control"
  )) #specify order of factor levels for factor_relevel

plot(mosaic.plot.data$condition,mosaic.plot.data$choice_letter,
  xlab = "Condition",
  ylab = "Bucket chosen")


#saving the plot with ggsave
# ggsave(
#   "./graphs/bucket_A_choices_BC.png",
#   plot = last_plot(),
#   device = NULL,
#  # path = "C:/Users/lonardol/Desktop/False Belief experiment/FB_2_follow_up/Graphs/Border Collies",
#   scale = 0.8,
#   width = 7,
#   height = 6,
#   #units = c("in", "cm", "mm"),
#   dpi = 320,
#   limitsize = TRUE
# )
```
```{r}
#chi square test (false belief - knowledge) 29 October
condition<-c("false belief", "knowledge", "control")
outcome <- plot.data$n.choseA # number of successes (bucket A chosen) for each condition
n <- plot.data$n.tested.per.cond # total trials for each condition

# Create a contingency table
table <- matrix(c(outcome[1], n[1] - outcome[1], outcome[2], n[2] - outcome[2], outcome[3], n[3] - outcome[3]), 
                nrow = 3, byrow = TRUE)
rownames(table) <- condition
colnames(table) <- c("Success", "Failure")

# Chi-squared test
chisq.test(table)
```
```{r}
#plot with error bars showing confidence intervals 
plot.data.ci <- plot.data %>%
  mutate(ci.lower = mean.choiceA - 1.96 * se.choiceA,
         ci.upper = mean.choiceA + 1.96 * se.choiceA)

# Now, plot with confidence intervals as error bars
p.choice.ci <- ggplot(data = plot.data.ci, aes(x = condition, y = mean.choiceA)) +
  geom_bar(stat = "identity", alpha = 0.5) +
  geom_errorbar(aes(ymin = ci.lower, ymax = ci.upper), width = 0.2) +
  #ylim(0,0.8)+
  #geom_signif(comparisons=list(c("False Belief", "Knowledge")), annotations="*",
  #             y_position = 0.75, tip_length = 0.04, vjust=0.4) +
  theme_classic() +
  labs(x = "Experimental group", y = "Proportion of bucket A choices") +
  ggtitle("All breeds (N=91)")

p.choice.ci
```


